name: Linter
run-name: ${{ github.actor }} Check Linter 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Run Linter
        run: yarn lint
